import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../providers.dart';
import '../models/chat_message.dart';
import '../services/api_service.dart';
import '../app_theme.dart';
import '../widgets/verdict_badge.dart';

class ChatTab extends ConsumerStatefulWidget {
  const ChatTab({super.key});

  @override
  ConsumerState<ChatTab> createState() => _ChatTabState();
}

class _ChatTabState extends ConsumerState<ChatTab> {
  final TextEditingController _controller = TextEditingController();
  final ScrollController _scrollController = ScrollController();
  bool _isLoading = false;

  void _sendMessage(String text) async {
    if (text.isEmpty) return;
    final sessionId = ref.read(chatSessionIdProvider);
    
    ref.read(chatMessagesProvider.notifier).addMessage(
      ChatMessage(role: 'user', content: text, timestamp: DateTime.now())
    );
    _controller.clear();
    setState(() => _isLoading = true);
    _scrollToBottom();

    try {
      final res = await ApiService.sendChat(message: text, sessionId: sessionId);
      ref.read(chatMessagesProvider.notifier).addMessage(
        ChatMessage(
          role: 'assistant',
          content: res['answer'] ?? res['content'] ?? '',
          timestamp: DateTime.now(),
          suggestedQuestions: List<String>.from(res['suggested_questions'] ?? []),
          dataConfidence: res['data_confidence']?.toString(),
          currentVerdict: res['current_verdict']?.toString(),
          currentScore: res['current_score'] as int?,
        ),
      );
    } catch (e) {
      ref.read(chatMessagesProvider.notifier).addMessage(
        ChatMessage(role: 'system', content: 'Error: $e', timestamp: DateTime.now(), isError: true)
      );
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
        _scrollToBottom();
      }
    }
  }

  void _scrollToBottom() {
    Future.delayed(const Duration(milliseconds: 100), () {
      if (_scrollController.hasClients) {
        _scrollController.animateTo(
          _scrollController.position.maxScrollExtent,
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeOut,
        );
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    final messages = ref.watch(chatMessagesProvider);
    return Column(
      children: [
        _buildContextBar(),
        Expanded(child: messages.isEmpty ? _buildEmptyState() : _buildMessageList(messages)),
        if (_isLoading) const LinearProgressIndicator(minHeight: 2),
        _buildInputBar(),
      ],
    );
  }

  Widget _buildContextBar() {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
      decoration: BoxDecoration(
        color: Theme.of(context).cardColor,
        border: const Border(bottom: BorderSide(color: Colors.white12)),
      ),
      child: Row(
        children: [
          const Icon(Icons.circle, color: AppTheme.green, size: 8),
          const SizedBox(width: 8),
          const Text('LIVE CONTEXT', style: TextStyle(fontSize: 10, fontWeight: FontWeight.bold, color: Colors.grey)),
          const Spacer(),
          ElevatedButton.icon(
            style: ElevatedButton.styleFrom(
              backgroundColor: AppTheme.primary,
              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
            ),
            onPressed: () async {
              // Show absolute loading configuration state safely
              showDialog(
                context: context,
                barrierDismissible: false,
                builder: (context) => const Center(
                  child: CircularProgressIndicator(color: AppTheme.primary),
                ),
              );

              try {
                // Call our upgraded report generation pipeline
                final res = await ApiService.triggerReport();
                final content = res['report_content'] ?? "No report generated.";
                final verdict = res['verdict'] ?? "NEUTRAL";
                Navigator.pop(context); // Dismiss loading spinner Safely

                // Present the dynamic system log generated by Gemini
                showModalBottomSheet(
                  context: context,
                  isScrollControlled: true,
                  backgroundColor: AppTheme.darkCard,
                  shape: const RoundedRectangleBorder(
                    borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
                  ),
                  builder: (context) => DraggableScrollableSheet(
                    initialChildSize: 0.7,
                    maxChildSize: 0.95,
                    expand: false,
                    builder: (context, scrollController) => SingleChildScrollView(
                      controller: scrollController,
                      padding: const EdgeInsets.all(24),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              const Text(
                                'QUANT PILOT AUDIT REPORT',
                                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.white),
                              ),
                              Container(
                                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                                decoration: BoxDecoration(
                                  color: res['verdict'] == 'BUY' ? AppTheme.green.withOpacity(0.2) : AppTheme.red.withOpacity(0.2),
                                  borderRadius: BorderRadius.circular(4),
                                ),
                                child: Text(
                                  "${res['verdict']}",
                                  style: TextStyle(color: res['verdict'] == 'BUY' ? AppTheme.green : AppTheme.red, fontWeight: FontWeight.bold, fontSize: 12),
                                ),
                              ),
                            ],
                          ),
                          const Divider(height: 24, color: Colors.white12),
                          Text(
                            res['report_content'] ?? 'No data generated.',
                            style: const TextStyle(color: Colors.white, fontSize: 13, height: 1.5),
                          ),
                        ],
                      ),
                    ),
                  ),
                );
              } catch (e) {
                Navigator.pop(context); // Close spinner on break exception point
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(content: Text('Failed to compile audit report: $e'), backgroundColor: AppTheme.red),
                );
              }
            },
            icon: const Icon(Icons.analytics, size: 14, color: Colors.white),
            label: const Text('GENERATE REPORT', style: TextStyle(fontSize: 10, color: Colors.white)),
          ),
        ],
      ),
    );
  }

  Widget _buildEmptyState() {
    final items = [
      {'q': 'Why did the model buy?', 'i': Icons.trending_up},
      {'q': 'Is now a good time to invest?', 'i': Icons.attach_money},
      {'q': 'What are the current environment risks?', 'i': Icons.warning},
      {'q': 'How confident is the model execution?', 'i': Icons.analytics},
    ];
    return Padding(
      padding: const EdgeInsets.all(24.0),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          const Icon(Icons.psychology_outlined, size: 64, color: AppTheme.primary),
          const SizedBox(height: 16),
          const Text('Ask the QuantPilot Analyst', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
          const Text('Powered by your RL model\'s live data telemetry', style: TextStyle(color: Colors.grey)),
          const SizedBox(height: 32),
          GridView.count(
            crossAxisCount: 2,
            shrinkWrap: true,
            mainAxisSpacing: 8,
            crossAxisSpacing: 8,
            childAspectRatio: 2.5,
            children: items.map((item) => ActionChip(
              avatar: Icon(item['i'] as IconData, size: 16, color: Colors.grey),
              label: Text(item['q'] as String, style: const TextStyle(fontSize: 11)),
              onPressed: () => _sendMessage(item['q'] as String),
            )).toList(),
          )
        ],
      ),
    );
  }

  Widget _buildMessageList(List<ChatMessage> messages) {
    return ListView.builder(
      controller: _scrollController,
      padding: const EdgeInsets.all(16),
      itemCount: messages.length,
      itemBuilder: (context, index) {
        final msg = messages[index];
        final isUser = msg.role == 'user';
        final isSystem = msg.role == 'system';

        if (isSystem) {
          return Center(
            child: Container(
              margin: const EdgeInsets.symmetric(vertical: 8),
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 6),
              decoration: BoxDecoration(
                color: msg.isError ? AppTheme.red.withOpacity(0.1) : Colors.white10,
                borderRadius: BorderRadius.circular(20),
              ),
              child: Text(
                msg.content,
                style: TextStyle(color: msg.isError ? AppTheme.red : Colors.grey, fontSize: 11),
              ),
            ),
          );
        }

        return Align(
          alignment: isUser ? Alignment.centerRight : Alignment.centerLeft,
          child: Column(
            crossAxisAlignment: isUser ? CrossAxisAlignment.end : CrossAxisAlignment.start,
            children: [
              Container(
                constraints: BoxConstraints(maxWidth: MediaQuery.of(context).size.width * 0.75),
                margin: const EdgeInsets.symmetric(vertical: 4),
                padding: const EdgeInsets.all(14),
                decoration: BoxDecoration(
                  color: isUser ? AppTheme.primary : Theme.of(context).cardColor,
                  borderRadius: BorderRadius.only(
                    topLeft: const Radius.circular(16),
                    topRight: const Radius.circular(16),
                    bottomLeft: Radius.circular(isUser ? 16 : 0),
                    bottomRight: Radius.circular(isUser ? 0 : 16),
                  ),
                  border: isUser ? null : Border.all(color: Theme.of(context).dividerColor),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    if (!isUser) ...[
                      const Text('QuantPilot AI Analyst', style: TextStyle(fontSize: 10, color: AppTheme.primary, fontWeight: FontWeight.bold)),
                      const SizedBox(height: 6),
                    ],
                    Text(msg.content, style: TextStyle(color: isUser ? Colors.white : Colors.white70, height: 1.4)),
                    
                    // Rich diagnostic telemetry mapping block
                    if (!isUser && (msg.currentVerdict != null || msg.dataConfidence != null)) ...[
                      const Divider(height: 16, color: Colors.white12),
                      Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          if (msg.currentVerdict != null) ...[
                            VerdictBadge(verdict: msg.currentVerdict!),
                            const SizedBox(width: 8),
                          ],
                          if (msg.dataConfidence != null)
                            Container(
                              padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                              decoration: BoxDecoration(color: Colors.white10, borderRadius: BorderRadius.circular(4)),
                              child: Text(
                                'Confidence: ${msg.dataConfidence}',
                                style: const TextStyle(fontSize: 9, color: Colors.grey),
                              ),
                            ),
                        ],
                      )
                    ]
                  ],
                ),
              ),
              // Render Follow-up Question Chips elegantly
              if (!isUser && msg.suggestedQuestions.isNotEmpty)
                Padding(
                  padding: const EdgeInsets.only(left: 4, top: 4, bottom: 12),
                  child: Wrap(
                    spacing: 6,
                    runSpacing: 6,
                    children: msg.suggestedQuestions.map((q) => ActionChip(
                      padding: EdgeInsets.zero,
                      label: Text(q, style: const TextStyle(fontSize: 10, color: AppTheme.primary)),
                      onPressed: () => _sendMessage(q),
                    )).toList(),
                  ),
                ),
            ],
          ),
        );
      },
    );
  }

  Widget _buildInputBar() {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
      color: Theme.of(context).cardColor,
      child: SafeArea(
        top: false,
        child: Row(
          children: [
            Expanded(
              child: TextField(
                controller: _controller,
                decoration: const InputDecoration(
                  hintText: 'Ask about the model\'s mathematical constraints...',
                  border: InputBorder.none,
                  hintStyle: TextStyle(color: Colors.grey, fontSize: 14),
                ),
                onSubmitted: _sendMessage,
              ),
            ),
            IconButton(
              icon: const Icon(Icons.send_rounded, color: AppTheme.primary),
              onPressed: () => _sendMessage(_controller.text),
            ),
          ],
        ),
      ),
    );
  }
}